#!/usr/bin/env python3
"""
threagile_dfd_to_html.py
Convert a Threagile data-flow-diagram .gv file into a self-contained HTML file
that exactly reproduces the Graphviz layout coordinates.

Usage:
  python threagile_dfd_to_html.py --dot data-flow-diagram.dot --out dfd.html
"""

import argparse
import base64
import functools
import html
import re
import shutil
import subprocess
import sys
import textwrap
from pathlib import Path

PPI = 72.0  # Graphviz points per inch
ICONS_DIR = Path(__file__).resolve().parent / "icons"

# ---------------------------------------------------------------------------
# Design tokens
# ---------------------------------------------------------------------------
# Editorial palette: neutral ink-on-paper everywhere, one accent color
# reserved for external/out-of-scope entities (Threagile's octagon shape) --
# the diagram's natural focal point -- rather than reusing Threagile's own
# color-by-asset-type palette. Font stays local (FreeSans, no network fetch)
# and matches what Graphviz itself resolves "Verdana" to when it computes
# node box sizes (see the CLAUDE.md/commit history on font substitution) --
# using a different font here without matching those metrics would overflow
# the pre-computed label boxes.
PAPER    = "#ffffff"
INK      = "#1a1a1a"
MUTED    = "#767676"
ACCENT   = "#1a3a5c"   # matches the report's own navy accent (report.css)
HAIRLINE = 1.25
RADIUS   = 6
FONT     = "FreeSans, sans-serif"

# Pastel fill ramps per trust-boundary type (Threagile's own enum -- see
# 00-threagile-field-reference.yml's trust_boundary_fields.type), solid
# rather than translucent so nested boundaries simply overpaint their own
# footprint within a parent's fill instead of the two compounding into a
# muddier color. Each type gets a shade list, lightest first -- when a
# boundary is nested inside one or more ancestors of the *same* type, each
# level one step further in gets the next shade in that type's own list, so
# the nesting itself stays visible instead of two same-type boundaries
# collapsing into one indistinguishable block of color. Real models observed
# nesting two deep for a given type; a 3rd shade is headroom, not tuned to a
# specific case. Depth is measured by geometric containment in build_svg,
# not DOT source order, since boundary nesting has no guaranteed text order.
#
# These are IL5 models, so the palette is deliberately green-dominant --
# green reads as "inside our accreditation boundary". network-cloud-provider
# is the one deliberate exception: its depth-0 shade is grey rather than a
# lighter green, because depth 0 of that type is always the outermost
# CSP-owned tenant/subscription (Azure Gov Environment, or an external IdP
# tenant like Entra ID -- both carry mgmt:csp-managed), which sits outside
# this system's own ATO boundary. Depth 1 of the same type is where a model
# actually enters its ATO boundary (System Environment, tagged
# scope:ato-boundary), so that's where the ramp switches to green -- grey
# vs. green marks a real trust-model distinction here, not just a nesting
# step, which is why this type's ramp changes hue instead of just shade.
BOUNDARY_FILL = {
    "network-cloud-provider": ["#e9e9e6", "#e6f4ea", "#cfe8d6"],
    "network-cloud-security-group": ["#d3ecda", "#b3ddbe", "#8fcc9f", "#6bbb80"],
    "network-policy-namespace-isolation": ["#eaf7ee", "#d8f0dd"],
    "network-on-prem": ["#e6ece7", "#d4e0d6", "#c2d4c5"],
    "network-dedicated-hoster": ["#e6ece7", "#d4e0d6", "#c2d4c5"],
    "network-virtual-lan": ["#eaf0ea", "#d8e4d8", "#c6d8c6"],
}

# execution-environment never nests inside another execution-environment
# (you don't put a VM inside a VM), so the ordinary "depth among same-type
# ancestors" rule below would always resolve it to shade 0 of its own list --
# a color that resets rather than continuing the surrounding hierarchy,
# which read as a disconnected, unrelated hue rather than "one level further
# in" the way every other nesting step in these diagrams reads. Instead it
# rides the *network-cloud-security-group* ramp above (the only type it's
# ever actually nested inside in practice -- a VM/host is always inside some
# subnet), counting depth among ancestors of that type instead of its own,
# so its fill is simply the next shade past its immediate parent subnet's
# own. See render_cluster's shade_depth/fill_type handling and the
# render_svg loop that computes FOLLOWS_RAMP_OF depth.
FOLLOWS_RAMP_OF = {
    "execution-environment": "network-cloud-security-group",
}

# ALTERNATE IMPACT-LEVEL PALETTES -- swap in for a higher-classification model
# by uncommenting exactly one block below (each reassigns BOUNDARY_FILL, so
# whichever block runs last wins -- uncommenting more than one silently
# discards all but the last). Every variant keeps the same depth-0 grey for
# network-cloud-provider (still means "outside our ATO boundary" regardless
# of classification) and was generated by hue-rotating the tuned IL5 green
# above at matching lightness/saturation per shade, so the same nesting-
# depth-by-shade logic still reads correctly -- these are untuned starting
# points, not visually verified the way the IL5 green above was, so give them
# a real look (e.g. the same real-Chromium-screenshot check used throughout
# this file's history) before actually shipping one.
#
# IL6 -- red
# BOUNDARY_FILL = {
#     "network-cloud-provider": ["#e9e6e6", "#f4e6e6", "#e8cfcf"],
#     "network-cloud-security-group": ["#ecd3d3", "#ddb3b3", "#cc8f8f", "#bb6b6b"],
#     "network-policy-namespace-isolation": ["#f7eaea", "#f0d8d8"],
#     "network-on-prem": ["#ece6e6", "#e0d4d4", "#d4c2c2"],
#     "network-dedicated-hoster": ["#ece6e6", "#e0d4d4", "#d4c2c2"],
#     "network-virtual-lan": ["#f0eaea", "#e4d8d8", "#d8c6c6"],
#     # execution-environment intentionally absent -- see FOLLOWS_RAMP_OF
#     # above; it rides this palette's own network-cloud-security-group list.
# }
#
# IL6+ -- yellow (first of three environments needing a distinct hue)
# BOUNDARY_FILL = {
#     "network-cloud-provider": ["#e9e8e6", "#f4f1e6", "#e8e3cf"],
#     "network-cloud-security-group": ["#ece7d3", "#ddd5b3", "#ccc08f", "#bbab6b"],
#     "network-policy-namespace-isolation": ["#f7f4ea", "#f0ebd8"],
#     "network-on-prem": ["#ecebe6", "#e0ded4", "#d4d0c2"],
#     "network-dedicated-hoster": ["#ecebe6", "#e0ded4", "#d4d0c2"],
#     "network-virtual-lan": ["#f0efea", "#e4e2d8", "#d8d4c6"],
#     # execution-environment intentionally absent -- see FOLLOWS_RAMP_OF above.
# }
#
# IL6+ -- purple (second environment)
# BOUNDARY_FILL = {
#     "network-cloud-provider": ["#e8e6e9", "#ede6f4", "#dccfe8"],
#     "network-cloud-security-group": ["#e0d3ec", "#c8b3dd", "#ad8fcc", "#926bbb"],
#     "network-policy-namespace-isolation": ["#f0eaf7", "#e4d8f0"],
#     "network-on-prem": ["#e9e6ec", "#dad4e0", "#cbc2d4"],
#     "network-dedicated-hoster": ["#e9e6ec", "#dad4e0", "#cbc2d4"],
#     "network-virtual-lan": ["#edeaf0", "#ded8e4", "#cfc6d8"],
#     # execution-environment intentionally absent -- see FOLLOWS_RAMP_OF above.
# }
#
# IL6+ -- orange (third environment)
# BOUNDARY_FILL = {
#     "network-cloud-provider": ["#e9e7e6", "#f4ede6", "#e8dbcf"],
#     "network-cloud-security-group": ["#ecdfd3", "#ddc7b3", "#ccab8f", "#bb8f6b"],
#     "network-policy-namespace-isolation": ["#f7f0ea", "#f0e3d8"],
#     "network-on-prem": ["#ece9e6", "#e0dad4", "#d4cac2"],
#     "network-dedicated-hoster": ["#ece9e6", "#e0dad4", "#d4cac2"],
#     "network-virtual-lan": ["#f0edea", "#e4ded8", "#d8cec6"],
#     # execution-environment intentionally absent -- see FOLLOWS_RAMP_OF above.
# }

# Fill per confidentiality level (Threagile's own enum, shared by data assets
# and technical assets -- see 00-threagile-field-reference.yml), used only on
# the data-asset diagram: it has no trust boundaries to shade, so this is its
# equivalent "what does the color mean" axis. Follows the common data-
# classification convention (public=green ... strictly-confidential=red)
# rather than reusing BOUNDARY_FILL's palette, so the two diagrams' colors
# aren't mistaken for encoding the same thing.
CONFIDENTIALITY_FILL = {
    "public": "#eaf7ee",
    "internal": "#eaf1fb",
    "restricted": "#fdf6e3",
    "confidential": "#fbe9dd",
    "strictly-confidential": "#fbe0e0",
}

# Pilot icon set, keyed by the value half of an `icon:*` tag (see
# 03-tags-lib.yml's "DIAGRAM ICON TAGS" section -- a dedicated tag namespace
# for this, deliberately separate from the security/hardening tags an asset
# also carries, since those can be many-per-asset and icon selection needs
# exactly one unambiguous choice). Values are the official Microsoft Azure
# architecture icon SVGs, vendored unmodified under icons/ -- Microsoft's
# terms of use permit this exact use (architecture diagrams) provided the
# icon isn't cropped, rotated, or distorted and represents the actual Azure
# product, which is why render_icon() embeds each file's untouched bytes via
# a data: URI <image> rather than re-drawing/recoloring their paths. Pilot
# covers only what confluence/llm-chat actually use today -- extend by
# dropping another vendored SVG into icons/ and adding an entry here.
# Values are paths relative to ICONS_DIR, one subfolder per cloud provider
# (icons/azure/, icons/aws/) so the same icon: tag namespace can grow to
# cover both without filename collisions between providers' own service names.
ICON_FILES = {
    "azure-waf": "azure/azure-waf.svg",
    "azure-ngfw": "azure/azure-ngfw.svg",
    "azure-vnet": "azure/azure-vnet.svg",
    "azure-aks": "azure/azure-aks.svg",
    "azure-key-vault": "azure/azure-key-vault.svg",
    "azure-database": "azure/azure-database.svg",
    "azure-storage": "azure/azure-storage.svg",
    "azure-monitor": "azure/azure-monitor.svg",
    "azure-avd": "azure/azure-avd.svg",
    "azure-entra-id": "azure/azure-entra-id.svg",
    "azure-private-link": "azure/azure-private-link.svg",
    "azure-subscription": "azure/azure-subscription.svg",
    # No public/private split in Azure's own icon set (unlike AWS's two
    # subnet icons below) -- one generic Subnet icon covers both.
    "azure-subnet": "azure/azure-subnet.svg",
    # Network Security Group -- a subnet-level security control, meant to
    # be tagged alongside icon:azure-subnet (both render as a row via
    # render_icon/render_cluster's multi-icon support), not instead of it.
    "azure-nsg": "azure/azure-nsg.svg",
    # AWS -- same 12-service pilot set, one tag per Azure counterpart above
    # (aws-vpc <-> azure-vnet, aws-eks <-> azure-aks, etc.), no app models
    # this yet but 05/06/07-*-lib.yml already have AWS sibling folders.
    "aws-waf": "aws/aws-waf.svg",
    "aws-ngfw": "aws/aws-ngfw.svg",
    "aws-vpc": "aws/aws-vpc.svg",
    "aws-eks": "aws/aws-eks.svg",
    "aws-secrets-manager": "aws/aws-secrets-manager.svg",
    "aws-database": "aws/aws-database.svg",
    "aws-storage": "aws/aws-storage.svg",
    "aws-monitor": "aws/aws-monitor.svg",
    "aws-workspaces": "aws/aws-workspaces.svg",
    "aws-identity-center": "aws/aws-identity-center.svg",
    "aws-private-link": "aws/aws-private-link.svg",
    "aws-organizations": "aws/aws-organizations.svg",
    "aws-cloud": "aws/aws-cloud.svg",
    # AWS's own official icon set splits this into two real, distinct
    # icons (same padlock glyph, different brand color) rather than one
    # generic subnet icon -- preserved as two tags rather than flattened
    # to match Azure's single icon/azure-subnet, since that distinction is
    # genuine AWS convention, not something invented here.
    "aws-subnet-public": "aws/aws-subnet-public.svg",
    "aws-subnet-private": "aws/aws-subnet-private.svg",
    # AWS has no equivalent to Azure NSG at all -- confirmed absent from
    # AWS's own official icon set (checked both the current and a prior
    # release). NACL is the real subnet-level analog structurally (both
    # apply at the subnet, unlike Security Groups which apply per
    # ENI/instance), even though NACLs are stateless where NSGs and
    # Security Groups are both stateful -- no single AWS construct matches
    # NSG on both dimensions, and subnet-level placement is what matters
    # for a boundary badge. Meant to be tagged alongside
    # icon:aws-subnet-public/private, not instead of it.
    "aws-nacl": "aws/aws-nacl.svg",
    # AWS-only additions beyond the paired pilot set above -- no Azure
    # counterpart tag, added as apps started modeling these services.
    "aws-bedrock": "aws/aws-bedrock.svg",
    "aws-api-gateway": "aws/aws-api-gateway.svg",
    "aws-alb": "aws/aws-alb.svg",
    "azure-app-gateway": "azure/azure-app-gateway.svg",
    "azure-load-balancer": "azure/azure-load-balancer.svg",
    "azure-openai": "azure/azure-openai.svg",
    "azure-management-groups": "azure/azure-management-groups.svg",
    # Kubernetes-native, not cloud-provider-specific -- one tag covers a
    # namespace boundary under either an AKS or EKS cluster (see 03-tags-lib.yml).
    "k8s-namespace": "opensource/k8s-namespace.svg",
    "kubernetes": "opensource/kubernetes.svg",
    # Software running as pods/processes inside an app's own compute,
    # independent of any cloud provider -- glyph + brand color on a 64x64
    # square, same visual language as the vendor sets above, built from
    # Simple Icons (CC0, simpleicons.org) glyphs recolored onto that
    # background rather than used as-provided (Simple Icons ships them as
    # bare monochrome glyphs with no fixed background of their own). The
    # folder is named "opensource" because every entry so far has been --
    # Confluence (commercial COTS, self-hosted the same way as these) is
    # the first exception, added to this same set/folder anyway since the
    # construction and selection logic are identical; only the license
    # differs, which nothing here keys off of.
    "keycloak": "opensource/keycloak.svg",
    "postgresql": "opensource/postgresql.svg",
    "nginx": "opensource/nginx.svg",
    "temporal": "opensource/temporal.svg",
    "qdrant": "opensource/qdrant.svg",
    "confluence": "opensource/confluence.svg",
    "splunk": "opensource/splunk.svg",
    "jira": "opensource/jira.svg",
    "gitlab": "opensource/gitlab.svg",
    "litellm": "opensource/litellm.svg",
    "k8s-secret-csi": "opensource/k8s-secret-csi.svg",
    "etcd": "opensource/etcd.svg",
    "guacamole": "opensource/guacamole.svg",
    "vault": "opensource/vault.svg",
    "grafana": "opensource/grafana.svg",
    "mcp": "opensource/mcp.svg",
    # Generic external-actor icons (not product logos) -- see icons/NOTICE.md.
    "human-web": "opensource/human-web.svg",
    "human-vdi": "opensource/human-vdi.svg",
    "machine-client": "opensource/machine-client.svg",
    # Generic boundary-type badge (not a product logo) for Threagile's own
    # execution-environment trust boundary type -- cloud-provider-
    # independent, same reasoning as kubernetes/k8s-namespace above. See
    # icons/NOTICE.md.
    "execution-environment": "opensource/execution-environment.svg",
    # Open WebUI's own official favicon (a raster PNG embedded in an SVG
    # wrapper, not a true vector like the Simple Icons ones above -- theirs
    # is the only logo asset that exists for it, and no separate background
    # square is added here since the favicon already is one, a white circle
    # around the black "OI" mark) -- see BRANDING.md in their repo for why
    # it's vendored unmodified rather than recolored to match the others.
    "open-webui": "opensource/open-webui.svg",
}

ICON_MARGIN = 3  # inset from the boundary's own corner (render_icon's anchor)

# Security-control icons (NSG/NACL) render in the boundary's top-LEFT corner
# instead of stacking into the same top-right row as the boundary's own
# identity icon (subnet, VNet/VPC, cluster, etc.) -- the two are different
# kinds of fact about a boundary (what it IS vs. what security control
# governs it), and cramming both into one corner read as clutter once a
# boundary carried both a subnet icon and its NSG/NACL pair. Keyed by
# ICON_FILES tag name (checked before resolving to a filename), not the
# filename itself. See render_cluster.
BOUNDARY_LEFT_CORNER_ICONS = frozenset({"azure-nsg", "aws-nacl"})

NODE_ICON_GAP  = 4   # vertical gap between a node's icon row and its label's first line
NODE_ICON_MIN  = 12  # floor to shrink a node's icon(s) to on a short/narrow box before giving up on them entirely -- still legible as a vector at this size
# Fixed size every node icon renders at, regardless of how much headroom
# its own box happens to have. This used to be a growth ceiling instead
# (up to a flat 64px cap, further limited to 0.45x of the box's own
# height) that let icon_size expand to fill whatever headroom a
# generously-scaled diagram's box had left over after the label -- which
# meant the same kind of icon rendered at visibly different sizes across
# one diagram depending purely on box geometry (a single-icon node vs. a
# two-icon node sharing a row, or a taller box vs. a shorter one), not on
# anything meaningful about the asset. Fixed value instead, so every node
# icon reads at the same visual weight; available_h/available_w below
# still shrink it (down to NODE_ICON_MIN) on a box too small to fit it.
# 30 matches what a two-icon node (AWS WAF + ALB sharing one row) already
# naturally worked out to under the old ratio-based formula on a typical
# box height in these diagrams -- picked as the new fixed default because
# it already read right in practice.
NODE_ICON_TARGET_SIZE = 30
NODE_ICON_ROW_GAP = 6  # horizontal gap between side-by-side icons when a node has more than one

# Trust boundary corner badge size (render_icon) -- intentionally the same
# size as a node's own primary icon (NODE_ICON_TARGET_SIZE) rather than a
# separate tuned value, so a boundary's identity/NSG-NACL badges read at
# the same visual weight as the asset icons inside it. Referencing
# NODE_ICON_TARGET_SIZE directly (rather than a separate literal) keeps
# the two from drifting apart, the same reasoning CLUSTER_FONTSIZE below
# already applies to node vs. boundary label text.
ICON_SIZE = NODE_ICON_TARGET_SIZE

# AWS's official icon set ships each glyph on a solid, edge-to-edge
# colored square (viewBox filled 100% in both dimensions, confirmed by
# rendering several AWS icons to a fixed size and measuring the actual
# non-transparent pixel bounding box) -- unlike Azure's, which are mostly
# transparent-background line art that doesn't reach the viewBox edges
# (measured ~60-63% fill in the narrower dimension for the same
# comparison). Both render at the exact same `width`/`height` <image> box
# (ICON_SIZE), but AWS icons have no built-in breathing room the way
# Azure's do, so they read as visibly larger/bolder at an identical box
# size -- most noticeable on trust boundary corner badges specifically,
# since that's where the icon sits directly against other diagram
# elements with no label to visually balance it (a node's primary icon
# always sits above the node's own label text, and so 100%-fill icons
# were not raised as an issue there). Scaling only render_icon() (the
# corner-badge call site), not render_icon_centered() (a node's own
# primary icon), which is the specific complaint this was raised against.
#
# Same correction applies to any icons/opensource/*.svg built with this
# repo's own full-bleed 64x64 background-square construction (see
# icons/NOTICE.md) when used as a boundary badge -- k8s-namespace.svg is
# the first, since it's the first opensource/ icon actually used on a
# trust boundary rather than only as a node's own primary icon. Not every
# opensource/ icon automatically needs this -- only ones actually placed
# via render_icon() -- so this is an explicit membership set (matching
# ICONS_NEEDING_PRINT_RASTER's own "don't add on suspicion alone"
# discipline), not an attempt to sniff full-bleed-ness from file content.
#
# The scale itself is 1.0 (no reduction) -- explicitly requested so a
# boundary badge always renders at exactly ICON_SIZE, matching a node's
# own icon size exactly rather than reading smaller for AWS/full-bleed
# icons specifically. Kept as a named constant (not inlined as 1.0 at the
# call site) so the visible-size-mismatch reasoning above stays attached
# to a real, easily-tunable knob if a future icon set brings the same
# full-bleed-vs-breathing-room mismatch back.
FULL_BLEED_BOUNDARY_ICON_SCALE = 1.0
FULL_BLEED_BOUNDARY_ICONS = frozenset({
    "opensource/k8s-namespace.svg",
})

# Node label font size -- a single shared constant rather than a literal
# repeated at both the call site that decides line-wrapping (wrap_and_fit,
# which needs to know it to compute how many characters fit per line) and
# the one that actually draws the text (render_node). Keeping those two in
# sync matters: wrapping decisions made against one size and rendered at a
# different one is exactly the kind of mismatch that overflows a box.
NODE_FONTSIZE  = 11
# The data-asset diagram's boxes are sized by Graphviz for the data-flow
# diagram's denser labels, so they end up generously wide relative to the
# data-asset diagram's own (often shorter) labels -- it can afford a much
# bigger node font than the data-flow diagram without wrapping trouble.
NODE_FONTSIZE_DATA_ASSET = 24
EDGE_FONTSIZE       = 10  # primary (solid) edges
EDGE_FONTSIZE_MINOR = 8   # dashed/background edges (telemetry, etc.) -- stays smaller than primary
CLUSTER_FONTSIZE = NODE_FONTSIZE  # trust-boundary label -- matches node label size (data-flow diagram only, the data-asset diagram has no trust boundaries). Was bumped to 14 at one point and read as oversized next to node text; referencing NODE_FONTSIZE directly (rather than a separate literal) keeps the two from drifting apart again.

# NODE_FONTSIZE/NODE_FONTSIZE_DATA_ASSET/CLUSTER_FONTSIZE/NODE_ICON_TARGET_SIZE/
# ICON_SIZE above are all fixed pixel sizes, but every diagram's own boxes
# render at a different effective scale (see build_svg's px_per_in): a
# diagram whose native Graphviz layout happens to come out narrower for its
# node count gets a larger px_per_in to fill the same target_width, so its
# boxes render visibly bigger in pixels than an equally-populated but wider
# diagram's -- confirmed directly comparing confluence (px_per_in ~50, a
# more compact native layout) against exposed-ai-chat (~32) at otherwise
# similar node counts. Left alone, that means the same fixed-pixel label
# text and icons read appropriately sized on one diagram and undersized
# relative to its own (bigger) boxes on another, purely as a function of
# each app's layout shape rather than anything to do with legibility.
# build_svg computes a per-diagram diagram_scale from px_per_in against
# this baseline and multiplies every one of those constants by it before
# rendering, so label/icon size tracks each diagram's own box size instead
# of everyone sharing one fixed pixel value regardless of scale. Baseline
# picked to equal exposed-ai-chat's own scale (the diagram these fixed
# sizes were last tuned and verified against), so diagram_scale is ~1.0
# there and the pixel constants above stay meaningful as "the size at
# exposed-ai-chat's own scale," not just an arbitrary multiplier base.
# Clamped so a real outlier (a diagram with only a couple of nodes, whose
# native graph can come out unusually small) can't blow font/icon size up
# or down to something absurd.
DIAGRAM_SCALE_BASELINE_PX_PER_IN = 32.0
DIAGRAM_SCALE_MIN = 0.6
DIAGRAM_SCALE_MAX = 1.8


@functools.lru_cache(maxsize=None)
def _icon_data_uri(filename: str) -> str:
    data = (ICONS_DIR / filename).read_bytes()
    b64 = base64.b64encode(data).decode("ascii")
    return f"data:image/svg+xml;base64,{b64}"


# Vendored icons confirmed (via an isolated minimal WeasyPrint render of
# each icon alone) to silently drop their gradient-filled background in
# WeasyPrint specifically -- browsers and cairosvg render every one of
# these correctly, so this is purely a WeasyPrint limitation, not a
# malformed file. Hardcoded to exactly what's been tested rather than
# sniffed from the SVG content: the first guess -- any icon whose
# gradientTransform includes rotate() -- was disproved by testing all 7
# vendored icons using gradientTransform individually (a from-scratch
# WeasyPrint render of each in isolation, one per icon, rasterized to PNG
# and visually inspected): azure-app-gateway.svg (rotate(45)) was the only
# one broken -- azure-vnet.svg's gradientTransform rotate(-0.08) (an
# effectively-zero rotation, likely a design-tool export artifact) and 5
# others all rendered correctly despite also using gradientTransform, so
# mere presence of the attribute -- or even of a rotate() inside it --
# isn't the real trigger. Re-test a new icon here individually (see this
# file's git history for the test harness) rather than assuming a pattern
# generalizes; don't add to this set on suspicion alone.
ICONS_NEEDING_PRINT_RASTER = frozenset({
    "azure/azure-app-gateway.svg",
    # azure-openai.svg shares azure-app-gateway.svg's own gradientTransform
    # rotate(45) pattern and was confirmed broken the same way (isolated
    # WeasyPrint render: 0% non-white pixels, fully blank) -- not added on
    # the rotate(45) pattern alone, per this set's own discipline above,
    # but on a real isolated test matching that one's actual result.
    "azure/azure-openai.svg",
})


def _icon_needs_print_raster(filename: str) -> bool:
    """See _icon_data_uri_raster and build_svg's for_print -- this never
    applies to the standalone SVG/HTML files, only the PDF-embedded copy."""
    return filename in ICONS_NEEDING_PRINT_RASTER


@functools.lru_cache(maxsize=None)
def _icon_data_uri_raster(filename: str) -> str:
    """PNG-rasterized fallback for _icon_needs_print_raster() icons, used
    only for the PDF-embedded diagram (see build_svg's for_print) -- the
    vendored SVG itself is never modified (icons/NOTICE.md's terms are
    about that file, not what we choose to embed it as), and the
    standalone SVG/HTML files keep embedding the original SVG unchanged,
    since only WeasyPrint has trouble with it.

    Reads a pre-rasterized <name>-print.png sitting next to the source
    SVG (fixed 256x256 -- every vendored icon is a square viewBox; final
    on-page size is always well under that, so this stays crisp at any
    size actually used) rather than calling cairosvg at report-render
    time. This used to rasterize on the fly via `cairosvg.svg2png(...)`,
    but the input (this one specific icon) and the output size never
    change, so the conversion only ever needs to happen once -- baking it
    in ahead of time removes cairosvg as a runtime dependency entirely,
    which matters on an air-gapped build where it may not be mirrored.
    Regenerate the PNG (`cairosvg.svg2png(url=..., output_width=256,
    output_height=256)` against the source SVG) only if that source SVG
    itself is ever replaced -- see icons/NOTICE.md."""
    svg_path = ICONS_DIR / filename
    png_path = svg_path.with_name(svg_path.stem + "-print.png")
    png_bytes = png_path.read_bytes()
    b64 = base64.b64encode(png_bytes).decode("ascii")
    return f"data:image/png;base64,{b64}"


def _resolve_icon_file(tag: str) -> str:
    """Looks up ICON_FILES[tag] and confirms the vendored SVG actually
    exists on disk. Returns "" (falsy) rather than raising for an
    unrecognized tag, since a model author can tag an asset with any
    icon: value regardless of whether this pilot set defines it yet --
    both render_icon() and render_icon_centered() treat that as "no icon"."""
    filename = ICON_FILES.get(tag)
    if not filename or not (ICONS_DIR / filename).exists():
        return ""
    return filename


def _icon_source(filename: str) -> str:
    """First path segment of a resolved ICON_FILES value, e.g. "azure" from
    "azure/azure-vnet.svg" -- looked up against ICON_SOURCE_SCALE."""
    return filename.split("/", 1)[0]


# The vendored aws/ and opensource/ icons both fill their full viewBox
# edge-to-edge with a solid colored square (confirmed: 13/14 aws/*.svg and
# 6/7 opensource/*.svg have an explicit <rect> spanning the whole canvas);
# azure/*.svg has none -- it's a transparent-canvas glyph with real margin
# around the artwork, by Microsoft's own icon design language. At the same
# ICON_SIZE, that used to read as visibly smaller/lighter next to an aws or
# opensource icon in the same node or diagram -- azure carried a 1.15x
# compensation here for exactly that. Once node icon size (and everything
# else pixel-sized) started scaling per-diagram against each diagram's own
# box size (see DIAGRAM_SCALE_BASELINE_PX_PER_IN), that visual mismatch
# stopped showing up in practice -- confirmed by the user's own visual
# review of confluence's regenerated diagram (all azure icons) right after
# that change landed -- so the compensation is no longer needed and every
# source now renders at its natural 1.0x. Kept as a dict (not deleted
# outright) in case a future icon set needs the same kind of per-vendor
# placement-size correction.
ICON_SOURCE_SCALE = {}


def _icon_href(filename: str, for_print: bool) -> str:
    """SVG data URI normally; PNG data URI when both for_print (this
    build_svg call is for the PDF-embedded diagram, not the standalone
    SVG/HTML files) and this specific icon needs the WeasyPrint workaround
    -- see _icon_needs_print_raster."""
    if for_print and _icon_needs_print_raster(filename):
        return _icon_data_uri_raster(filename)
    return _icon_data_uri(filename)


def render_icon(corner_x: float, top_y: float, tags, color: str,
                 for_print: bool = False, anchor: str = "right",
                 icon_size: float = ICON_SIZE) -> str:
    """Places a small row of vendored icons/ICON_FILES[tag] SVGs inset from
    (corner_x, top_y) -- one of a trust boundary/cluster's own top corners
    -- as a supplementary corner badge row: one icon per tag in `tags`.
    anchor="right" (default) treats corner_x as the boundary's top-right
    corner, flush-right with additional icons extending leftward (e.g. a
    subnet's own identity icon). anchor="left" treats corner_x as the
    top-left corner instead, flush-left with additional icons extending
    rightward -- used for security-control icons (NSG/NACL), kept in the
    opposite corner from the identity icon rather than stacked into the
    same row with it (see BOUNDARY_LEFT_CORNER_ICONS). `tags` may be a
    single string (kept for callers with just one) or a list/tuple for
    more. `color` is unused (kept so call sites don't need to know whether
    the active icon set is hand-drawn or vendored artwork) -- these icons
    carry Microsoft's/AWS's own official per-service colors, and
    recoloring them would run afoul of the "don't distort" terms of use.
    icon_size defaults to the flat ICON_SIZE but build_svg passes its own
    per-diagram scaled value instead (see DIAGRAM_SCALE_BASELINE_PX_PER_IN)."""
    if isinstance(tags, str):
        tags = [tags]
    filenames = [f for f in (_resolve_icon_file(t) for t in tags) if f]
    if not filenames:
        return ""
    out = []
    cursor = corner_x + ICON_MARGIN if anchor == "left" else corner_x - ICON_MARGIN
    for filename in filenames:
        # See FULL_BLEED_BOUNDARY_ICON_SCALE's own comment: AWS's icons
        # (and FULL_BLEED_BOUNDARY_ICONS) fill their own viewBox
        # edge-to-edge with no built-in margin the way Azure's do, so they
        # read as visibly larger at an identical box size. Scaled (not
        # just repositioned) so the badge itself shrinks, computed per
        # icon (not once for the whole row) so a mixed row -- e.g. an
        # unscaled icon:azure-nsg next to an unscaled icon:azure-subnet --
        # doesn't force every icon in the row down to whichever one
        # happens to need scaling.
        needs_scale = filename.startswith("aws/") or filename in FULL_BLEED_BOUNDARY_ICONS
        size = icon_size * FULL_BLEED_BOUNDARY_ICON_SCALE if needs_scale else icon_size
        x = cursor if anchor == "left" else cursor - size
        y = top_y + ICON_MARGIN
        href = _icon_href(filename, for_print)
        out.append(f'<image href="{href}" x="{x:.2f}" y="{y:.2f}" '
                    f'width="{size}" height="{size}"/>')
        cursor = (x + size + NODE_ICON_ROW_GAP) if anchor == "left" else (x - NODE_ICON_ROW_GAP)
    return "\n".join(out)


def render_icon_centered(cx: float, top_y: float, tag: str, size: float = NODE_ICON_TARGET_SIZE, for_print: bool = False) -> str:
    """Places the vendored icons/ICON_FILES[tag] SVG horizontally centered
    on cx with its top edge at top_y, at the given size (defaulting to
    NODE_ICON_TARGET_SIZE) -- used for a node's own primary icon (see
    render_node), as opposed to a boundary's corner badge (render_icon).
    render_node's only caller always passes size explicitly (shrunk below
    the default on a short box rather than let the icon+label block
    overflow it); the default here exists only as a safe fallback for any
    other caller."""
    filename = _resolve_icon_file(tag)
    if not filename:
        return ""
    href = _icon_href(filename, for_print)
    x = cx - size / 2
    return (f'<image href="{href}" x="{x:.2f}" y="{top_y:.2f}" '
            f'width="{size}" height="{size}"/>')


# ---------------------------------------------------------------------------
# 1. Run dot -Tplain
# ---------------------------------------------------------------------------

def run_dot_plain(dot_source: str) -> str:
    dot_bin = shutil.which("dot")
    if not dot_bin:
        sys.exit("ERROR: 'dot' (Graphviz) not found on PATH.")
    result = subprocess.run(
        [dot_bin, "-Tplain"],
        input=dot_source.encode(),
        capture_output=True,
    )
    if result.returncode != 0:
        sys.exit("ERROR: dot failed:\n" + result.stderr.decode(errors="replace"))
    return result.stdout.decode(errors="replace")


# ---------------------------------------------------------------------------
# 2. Parse plain output
# ---------------------------------------------------------------------------

def _tokenise(line: str) -> list:
    """Tokenise respecting quoted strings and HTML angle-bracket labels."""
    tokens = []
    i = 0
    while i < len(line):
        if line[i].isspace():
            i += 1
            continue
        if line[i] == '"':
            j = i + 1
            while j < len(line):
                if line[j] == '"' and line[j-1] != '\\':
                    break
                j += 1
            tokens.append(line[i+1:j].replace('\\"', '"'))
            i = j + 1
        elif line[i] == '<':
            depth = 0
            j = i
            while j < len(line):
                if line[j] == '<': depth += 1
                elif line[j] == '>':
                    depth -= 1
                    if depth == 0:
                        break
                j += 1
            tokens.append(line[i:j+1])
            i = j + 1
        else:
            j = i
            while j < len(line) and not line[j].isspace():
                j += 1
            tokens.append(line[i:j])
            i = j
    return tokens


def strip_html(s: str) -> str:
    """Extract plain text from an HTML label."""
    s = s.strip()
    # Remove outer < > wrapper
    if s.startswith('<') and s.endswith('>'):
        s = s[1:-1]
    # Strip all HTML tags
    s = re.sub(r'<[^>]+>', ' ', s)
    # Decode entities
    s = s.replace('&lt;', '<').replace('&gt;', '>').replace('&amp;', '&').replace('&quot;', '"').replace('&nbsp;', ' ')
    # Collapse whitespace
    s = re.sub(r'\s+', ' ', s).strip()
    return s


def extract_bold_text(s: str) -> str:
    """Extract the asset name from a Threagile HTML table label.
    Threagile uses: <b><font color=...>Asset Name</font></b>

    Threagile HTML-escapes the label text itself (e.g. an asset titled
    "... & ..." becomes "... &amp; ..." in the DOT source), so the raw
    regex match needs unescaping -- otherwise it round-trips as literal
    "&amp;" both when matching this text against the model YAML's asset
    titles (confidentiality_by_label) and when it gets re-escaped for SVG
    output, doubling up into a visibly wrong "&amp;amp;".
    """
    s = s.strip()
    if s.startswith('<') and s.endswith('>'):
        s = s[1:-1]

    # Primary: <b><font ...>TEXT</font></b>
    m = re.search(r'<b[^>]*><font[^>]*>([^<]+)</font></b>', s)
    if m:
        return html.unescape(m.group(1).strip())

    # Secondary: <b>TEXT</b> with optional nested tags
    m = re.search(r'<b[^>]*>(?:<[^>]+>)?([^<]+)(?:<[^>]+>)?</b>', s)
    if m:
        return html.unescape(m.group(1).strip())

    # Fallback: strip all tags
    text = re.sub(r'<[^>]+>', ' ', s)
    text = re.sub(r'\s+', ' ', text).strip()
    return html.unescape(text)


def parse_plain(plain: str) -> dict:
    nodes = {}
    edges = []
    graph_info = {}
    STYLES = {"solid", "dashed", "dotted", "bold", "invis", "filled"}

    for raw_line in plain.splitlines():
        t = _tokenise(raw_line)
        if not t:
            continue

        if t[0] == "graph":
            graph_info = {
                "scale":  float(t[1]),
                "width":  float(t[2]),
                "height": float(t[3]),
            }

        elif t[0] == "node":
            nid       = t[1]
            x, y      = float(t[2]), float(t[3])
            w, h      = float(t[4]), float(t[5])
            raw_label = t[6] if len(t) > 6 else nid
            style     = t[7] if len(t) > 7 else "solid"
            shape     = t[8] if len(t) > 8 else "ellipse"
            color     = t[9] if len(t) > 9 else "black"
            fillcolor = t[10] if len(t) > 10 else "white"

            # Prefer label from DOT source attrs (more reliable for HTML table labels)
            label = extract_bold_text(raw_label)
            if not label or label in (r'\N', '\\N') or label == nid:
                label = nid  # will be overridden later from dot_attrs

            nodes[nid] = dict(
                id=nid, x=x, y=y, w=w, h=h,
                label=label, style=style, shape=shape,
                color=color, fillcolor=fillcolor,
            )

        elif t[0] == "edge":
            tail = t[1]
            head = t[2]
            n    = int(t[3])
            pts  = []
            idx  = 4
            for _ in range(n):
                pts.append((float(t[idx]), float(t[idx+1])))
                idx += 2
            label = ""
            lx, ly = None, None
            if idx < len(t) and t[idx] not in STYLES:
                label = strip_html(t[idx]); idx += 1
                if idx + 1 < len(t):
                    try:
                        lx, ly = float(t[idx]), float(t[idx+1])
                        idx += 2
                    except ValueError:
                        pass
            style = t[idx]   if idx   < len(t) else "solid"
            color = t[idx+1] if idx+1 < len(t) else "#999999"
            edges.append(dict(
                tail=tail, head=head, points=pts,
                label=label, lx=lx, ly=ly,
                style=style, color=color,
            ))

    return dict(graph=graph_info, nodes=list(nodes.values()), edges=edges)


# ---------------------------------------------------------------------------
# 3. Extract node attributes from DOT source
# ---------------------------------------------------------------------------

def parse_dot_node_attrs(dot_source: str) -> dict:
    """Extract per-node attributes directly from DOT source."""
    attrs = {}
    # Match node blocks: ID [ ... ]; handling multiline. Anchored to the
    # start of a line (after only whitespace) -- an unanchored \d+\[...\];
    # also matches an edge's *head* id ("4069313389 -> 735278355 [ ... ];"
    # -- "735278355" isn't at the start of that line, but the pattern
    # doesn't care), and since a node id can coincide with some edge's head
    # id elsewhere in the file, an unanchored match can silently clobber
    # this dict's entry for that node with the edge's own attrs instead
    # (confirmed: happened for a real node in exposed-ai-chat's diagram,
    # corrupting the "better bold label" override this feeds elsewhere).
    pattern = re.compile(r'^[ \t]*(\d+)\s*\[\s*\n?(.*?)\s*\]\s*;', re.DOTALL | re.MULTILINE)
    for m in pattern.finditer(dot_source):
        nid  = m.group(1)
        body = m.group(2)
        d    = {}
        # Extract key=<html_label> using depth tracking
        pos = 0
        while pos < len(body):
            km = re.search(r'(\w+)\s*=\s*', body[pos:])
            if not km: break
            kstart = pos + km.start()
            vstart = pos + km.end()
            k = km.group(1)
            pos = vstart
            if pos >= len(body): break
            if body[pos] == '<':
                # HTML label - track depth
                depth = 0
                j = pos
                while j < len(body):
                    if body[j] == '<': depth += 1
                    elif body[j] == '>':
                        depth -= 1
                        if depth == 0:
                            break
                    j += 1
                d[k] = body[pos:j+1]
                pos = j + 1
            elif body[pos] == '"':
                j = pos + 1
                while j < len(body) and not (body[j] == '"' and body[j-1] != '\\'):
                    j += 1
                d[k] = body[pos+1:j]
                pos = j + 1
            else:
                j = pos
                while j < len(body) and body[j] not in (' ', '\t', '\n', ',', ']'):
                    j += 1
                d[k] = body[pos:j]
                pos = j
        attrs[nid] = d
    return attrs


def _extract_angle_bracket(text: str, start: int):
    """Extract a full <<...>> HTML label respecting nested angle brackets."""
    if start >= len(text) or text[start] != '<':
        return None, start
    depth = 0
    i = start
    while i < len(text):
        if text[i] == '<': depth += 1
        elif text[i] == '>':
            depth -= 1
            if depth == 0:
                return text[start:i+1], i+1
        i += 1
    return None, start


def _iter_clusters(dot_source: str):
    """
    Yield (cluster_id, graph_attrs_block) for every cluster in the DOT source,
    handling arbitrary nesting depth by tracking brace depth manually.
    graph_attrs_block is the text inside the 'graph [ ... ]' statement of that cluster.
    """
    i = 0
    n = len(dot_source)
    # Find every occurrence of 'subgraph cluster_NNN {'
    header_re = re.compile(r'subgraph\s+cluster_(\d+)\s*\{', re.DOTALL)
    for hm in header_re.finditer(dot_source):
        cid = hm.group(1)
        # Find the graph [ ... ] block immediately inside this cluster
        # It starts right after the opening brace
        body_start = hm.end()
        # Extract just the graph [...] portion (first graph [...] inside)
        gm = re.search(r'\bgraph\s*\[', dot_source[body_start:body_start+2000])
        if not gm:
            continue
        bracket_start = body_start + gm.end() - 1  # position of '['
        # Find matching ']' tracking depth
        depth = 0
        j = bracket_start
        while j < n:
            if dot_source[j] == '[': depth += 1
            elif dot_source[j] == ']':
                depth -= 1
                if depth == 0:
                    break
            j += 1
        graph_block = dot_source[bracket_start+1:j]
        yield cid, graph_block


def parse_dot_cluster_attrs(dot_source: str) -> list:
    """Extract cluster subgraph labels and styles, skipping layout-only spacers."""
    clusters = []
    seen = set()
    for cid, graph_block in _iter_clusters(dot_source):
        if cid in seen:
            continue

        # Skip invisible spacer clusters
        style_m = re.search(r'\bstyle\s*=\s*"([^"]*)"', graph_block)
        style = style_m.group(1) if style_m else "dashed"
        if "invis" in style:
            continue

        # Extract label and, separately, the trust-boundary type suffix --
        # Threagile renders it as plain text after the closing </b>, e.g.
        # "<b>DMZ VNet</b> (network-cloud-security-group)", so it's never
        # part of the bold-name match below and has to be pulled out on its
        # own rather than stripped off the end of label.
        label = ""
        boundary_type = ""
        lm = re.search(r'label\s*=\s*(<)', graph_block)
        if lm:
            raw, _ = _extract_angle_bracket(graph_block, lm.start(1))
            if raw:
                type_m = re.search(r'</b>\s*\(([a-z][a-z-]*)\)', raw)
                if type_m:
                    boundary_type = type_m.group(1)
                # Match <b><font ...>NAME</font></b>. Threagile HTML-escapes
                # the label text (see extract_bold_text), so unescape here
                # too -- otherwise a boundary name containing e.g. "&" would
                # round-trip as literal "&amp;" once re-escaped for SVG output.
                bm = re.search(r'<b[^>]*><font[^>]*>([^<]+)</font></b>', raw)
                if bm:
                    label = html.unescape(bm.group(1).strip())
                else:
                    # Fallback: any <b>TEXT</b>
                    bm2 = re.search(r'<b[^>]*>([^<]+)</b>', raw)
                    if bm2:
                        label = html.unescape(bm2.group(1).strip())
        if not label:
            lm2 = re.search(r'label\s*=\s*"([^"]*)"', graph_block)
            if lm2:
                label = html.unescape(lm2.group(1).strip())
        if not label:
            continue
        # Strip trust boundary type suffix e.g. " (network-cloud-provider)"
        # in case it ended up inside the matched label text after all.
        label = re.sub(r'\s*\([^)]+\)\s*$', '', label).strip()

        color_m    = re.search(r'\bcolor\s*=\s*"([^"]*)"',    graph_block)
        bgcolor_m  = re.search(r'\bbgcolor\s*=\s*"([^"]*)"',  graph_block)
        penwidth_m = re.search(r'\bpenwidth\s*=\s*"([^"]*)"', graph_block)

        color    = color_m.group(1)    if color_m    else "#3A52C8"
        bgcolor  = bgcolor_m.group(1)  if bgcolor_m  else "none"
        penwidth = float(penwidth_m.group(1)) if penwidth_m else 2.0

        seen.add(cid)
        clusters.append(dict(
            id=cid, label=label, color=color, boundary_type=boundary_type,
            bgcolor=bgcolor, style=style, penwidth=penwidth,
        ))
    return clusters


def parse_dot_edge_xlabels(dot_source: str) -> dict:
    """Extract xlabel attributes from edges in DOT source. Returns {(tail,head): label}."""
    xlabels = {}
    for m in re.finditer(r'(\d+)\s*->\s*(\d+)\s*\[([^\]]+)\]', dot_source, re.DOTALL):
        tail, head = m.group(1), m.group(2)
        xl = re.search(r'xlabel\s*=\s*"([^"]+)"', m.group(3))
        if xl:
            xlabels[(tail, head)] = xl.group(1)
    return xlabels


def parse_dot_cluster_bbs(dot_source: str) -> tuple:
    """
    Run dot -Tdot to get:
      - bb= bounding boxes for all clusters  → dict {cluster_id: [x0,y0,x1,y1]}
      - xlp= label positions for all edges   → dict {(tail,head): (x,y)} in points

    Returns (bbs, xlp_positions).
    """
    dot_bin = shutil.which("dot")
    if not dot_bin:
        return {}, {}
    try:
        result = subprocess.run(
            [dot_bin, "-Tdot"],
            input=dot_source.encode(),
            capture_output=True,
            timeout=30,
        )
        if result.returncode != 0:
            return {}, {}
        annotated = result.stdout.decode(errors="replace")
    except Exception:
        return {}, {}

    # Cluster bounding boxes
    bbs = {}
    for cid, graph_block in _iter_clusters(annotated):
        bb_m = re.search(r'\bbb\s*=\s*"([^"]+)"', graph_block)
        if bb_m:
            parts = [float(v) for v in bb_m.group(1).split(",")]
            if len(parts) == 4:
                bbs[cid] = parts

    # Edge xlabel positions (xlp attribute in dot -Tdot output)
    xlp = {}
    for m in re.finditer(
        r'(\d+)\s*->\s*(\d+)\s*\[([^\]]*xlp\s*=\s*"[^"]*"[^\]]*)\]',
        annotated, re.DOTALL
    ):
        tail, head, attrs = m.group(1), m.group(2), m.group(3)
        xlp_m = re.search(r'xlp\s*=\s*"([^"]+)"', attrs)
        if xlp_m:
            coords = [float(v) for v in xlp_m.group(1).split(",")]
            if len(coords) == 2:
                xlp[(tail, head)] = (coords[0], coords[1])

    return bbs, xlp


# ---------------------------------------------------------------------------
# 4. Color helpers
# ---------------------------------------------------------------------------

_NAMED = {
    "white": "#ffffff", "black": "#000000", "blue": "#0000ff",
    "red": "#ff0000", "green": "#008000", "gray": "#808080",
    "grey": "#808080", "lightgrey": "#d3d3d3", "none": "none",
}

def to_hex(c: str) -> str:
    if not c: return "#000000"
    c = c.strip().strip('"')
    if c.startswith('#'): return c
    return _NAMED.get(c.lower(), c)

def luminance(h: str) -> float:
    h = h.lstrip('#')
    if len(h) == 3: h = h[0]*2+h[1]*2+h[2]*2
    if len(h) != 6: return 0.5
    r,g,b = int(h[0:2],16),int(h[2:4],16),int(h[4:6],16)
    return (0.299*r+0.587*g+0.114*b)/255

def text_color(bg: str) -> str:
    bg = to_hex(bg)
    if bg == "none": return "#333333"
    return "#ffffff" if luminance(bg) < 0.55 else "#111111"


# ---------------------------------------------------------------------------
# 5. SVG shape renderers
# ---------------------------------------------------------------------------

def svg_rect(cx, cy, w, h, fill, stroke, sw, rx=6, dash=""):
    da = f' stroke-dasharray="{dash}"' if dash else ""
    return (f'<rect x="{cx-w/2:.2f}" y="{cy-h/2:.2f}" width="{w:.2f}" height="{h:.2f}" '
            f'rx="{rx}" fill="{fill}" stroke="{stroke}" stroke-width="{sw:.1f}"{da}/>')

def wrap_label(text: str, max_width: float, fontsize: float) -> list:
    """Greedy word-wrap to fit max_width, estimating FreeSans's average
    character width rather than measuring exactly (no font-metrics library
    in play here) -- 0.6x fontsize is a safe-ish upper bound for mixed-case
    text in this font. Needed because a node's *native* Graphviz box size
    can be generous while still rendering small after the whole diagram is
    scaled down to fit the page, at which point a fixed font-size can
    overflow it (confirmed: e.g. a 4in-wide native box that's still too
    narrow for one line of an unwrapped 24-character label once scaled)."""
    max_chars = max(4, int(max_width / (fontsize * 0.6)))
    words = text.split()
    lines, cur = [], ""
    for word in words:
        candidate = f"{cur} {word}".strip()
        if len(candidate) <= max_chars or not cur:
            cur = candidate
        else:
            lines.append(cur)
            cur = word
    if cur:
        lines.append(cur)
    return lines or [text]


def wrap_and_fit(label: str, native_w: float, fontsize: float) -> tuple:
    """Word-wraps label against the node's native Graphviz width. Returns
    (lines, native_w) -- the width is intentionally left untouched.

    An earlier version of this function shrank the returned width to fit
    the wrapped content, on the theory that Graphviz's box (sized for its
    own native, larger-font label) was often wider than our smaller
    restyled text needed. That's true, but Graphviz's *edge routing* --
    the actual spline points, not just the final clip point -- was
    computed against the original wide silhouette. Shrinking the box out
    from under an already-routed edge left _clip_and_shift dragging the
    endpoint to a boundary the rest of the path was never drawn to reach,
    producing visibly disconnected ("floating") arrows on edges that
    approached from the side rather than square-on. Node height was never
    part of that problem (see NODE_ICON_* / the content-block centering in
    render_node) since nothing there moves where a node's boundary is."""
    lines = wrap_label(label, native_w * 0.85, fontsize)
    return lines, native_w


def render_node(node: dict, cx: float, cy: float, w: float, h: float,
                dot_attrs: dict, lines: list, fill_override: str = None, icon_tags: list = None,
                fontsize: float = NODE_FONTSIZE, for_print: bool = False,
                icon_target_size: float = NODE_ICON_TARGET_SIZE) -> str:
    """lines is the label already word-wrapped by the caller (see
    _wrap_and_measure) -- computed once against the node's *original*
    Graphviz width so wrapping decisions stay stable even when w here has
    since been tightened to a smaller, content-fit value (see build_svg's
    node-sizing pass). Re-wrapping against the already-shrunk w here would
    risk wrapping the same label differently than what that shrink amount
    was actually computed for."""
    nid   = node["id"]
    extra = dot_attrs.get(nid, {})

    shape  = extra.get("shape", node["shape"]).lower()
    style  = extra.get("style", node["style"]).lower()
    periph = int(extra.get("peripheries", "1"))

    # Accent reserved for external/out-of-scope entities (Threagile's own
    # octagon convention) -- the diagram's natural focal point, signaled via
    # a bold accent-colored border rather than a solid accent fill (solid
    # navy read as visually heavier than intended and made the node's own
    # label/icon harder to read against it). Everything else is neutral
    # ink-on-paper regardless of Threagile's own color-by-asset-type fill,
    # per the one-accent-color principle. fill_override (confidentiality-
    # level fill, data-asset diagram only) takes the paper slot when given.
    is_accent = shape == "octagon"
    fill      = fill_override or PAPER
    stroke    = ACCENT if is_accent else INK
    sw        = HAIRLINE

    dash = "5,3" if "dotted" in style else ("8,4" if "dashed" in style else "")

    # Every node draws as a plain rect regardless of Threagile's own shape
    # (ellipse/cylinder/octagon) -- a flat arrowhead meeting a flat,
    # perpendicular boundary sits flush with no overlap, sidestepping the
    # curve-vs-flat-marker mismatch entirely rather than continuing to
    # tune clip/gap math against it. `shape` (Threagile's original) is
    # still consulted below for the external/out-of-scope accent color,
    # which is a semantic distinction independent of the drawn geometry.
    shape_svg = svg_rect(cx, cy, w, h, fill, stroke, sw, rx=RADIUS, dash=dash)

    # Double border (peripheries=2) — draw a second slightly smaller rect
    periph_svg = ""
    if periph >= 2:
        inset = sw * 2 + 2
        periph_svg = svg_rect(cx, cy, w-inset, h-inset, "none", stroke, sw*0.6, rx=RADIUS-2)

    fc       = text_color(fill)
    line_h   = fontsize * 1.4
    total_h  = line_h * len(lines)

    # A node's icon(s) (when tagged) are its primary visual identifier, not
    # a supplementary corner badge -- stack them above the label and center
    # the whole thing as one block, so it never competes with the label for
    # space regardless of box size or how many lines the label wraps to.
    # More than one icon tag (e.g. an ALB tagged both icon:aws-waf and
    # icon:aws-alb) sits as a single side-by-side row, in tag order. Nodes
    # without an icon keep the plain vertically-centered label.
    #
    # Graphviz's own box height is sized for its native (larger-font,
    # multi-row) label, not our own restyled single-line-per-row text at a
    # much smaller font -- on a short box a 2-line wrapped label alone can
    # already use most of that height, leaving no room for a full-size
    # icon row on top. Shrink the icon row (down to NODE_ICON_MIN per icon)
    # to whatever fits above the text rather than let the block overflow
    # the box, and drop it entirely if even the floor size doesn't fit --
    # checked against both the box's remaining height (as before) and, for
    # more than one icon, its width too, so a row of icons can't run wider
    # than the box just because there happened to be room vertically.
    node_icon_svg = ""
    icon_tags = [t for t in (icon_tags or []) if _resolve_icon_file(t)]
    if icon_tags:
        n           = len(icon_tags)
        available_h = max(0.0, h * 0.92 - total_h - NODE_ICON_GAP)
        icon_size   = min(icon_target_size, available_h)
        if n > 1:
            available_w = max(0.0, w * 0.92 - (n - 1) * NODE_ICON_ROW_GAP)
            icon_size   = min(icon_size, available_w / n)
        if icon_size >= NODE_ICON_MIN:
            block_h   = icon_size + NODE_ICON_GAP + total_h
            block_top = cy - block_h / 2
            row_w     = n * icon_size + (n - 1) * NODE_ICON_ROW_GAP
            row_left  = cx - row_w / 2
            for i, tag in enumerate(icon_tags):
                icon_cx    = row_left + i * (icon_size + NODE_ICON_ROW_GAP) + icon_size / 2
                # icon_size above is the reserved layout footprint (drives
                # block_h/row_w/the gap to the label) and stays fixed
                # regardless of source, so wrapping/box-fit math above is
                # unaffected -- only the drawn image is scaled per
                # ICON_SOURCE_SCALE, inset so it's still centered in that
                # same reserved cell rather than shifted toward one edge.
                scale      = ICON_SOURCE_SCALE.get(_icon_source(_resolve_icon_file(tag)), 1.0)
                drawn_size = icon_size * scale
                icon_top   = block_top + (icon_size - drawn_size) / 2
                node_icon_svg += render_icon_centered(icon_cx, icon_top, tag, size=drawn_size, for_print=for_print)
            start_y = block_top + icon_size + NODE_ICON_GAP + line_h * 0.8
        else:
            start_y = cy - total_h / 2 + line_h * 0.8
    else:
        start_y = cy - total_h / 2 + line_h * 0.8

    text_parts = []
    for i, line in enumerate(lines):
        y = start_y + i * line_h
        text_parts.append(
            f'<text x="{cx:.2f}" y="{y:.2f}" text-anchor="middle" '
            f'font-size="{fontsize}" font-weight="700" '
            f'font-family="{FONT}" fill="{fc}">'
            f'{html.escape(line)}</text>'
        )

    return shape_svg + "\n" + periph_svg + "\n" + "\n".join(text_parts) + "\n" + node_icon_svg


# ---------------------------------------------------------------------------
# 6. Edge renderer
# ---------------------------------------------------------------------------

def _pts_close(a: tuple, b: tuple, eps: float = 0.01) -> bool:
    return abs(a[0] - b[0]) < eps and abs(a[1] - b[1]) < eps


def _clip_to_box(qx: float, qy: float, px: float, py: float,
                  cx: float, cy: float, hw: float, hh: float) -> tuple:
    """Where the ray from Q=(qx,qy) through P=(px,py) crosses the boundary
    of the axis-aligned box centered at (cx,cy) with half-width/height
    hw/hh -- used to snap an edge's endpoint exactly onto its node's
    boundary. Needed because dot -Tplain's own spline endpoints sometimes
    fall short of (or past) the actual node boundary by a visible amount --
    confirmed directly in Graphviz's raw plain-text output for one such
    edge, not something introduced by our own coordinate handling -- so we
    do the clipping ourselves rather than trusting that point as-is.

    Every node renders as a plain rect (see render_node), so this is the
    only clip shape needed -- a flat marker meeting this boundary head-on
    sits flush with no overlap, unlike the curved shapes this used to also
    have to handle.
    """
    dx, dy = px - qx, py - qy
    if dx == 0 and dy == 0:
        return px, py
    candidates = []
    if dx != 0:
        for bx in (cx - hw, cx + hw):
            t = (bx - qx) / dx
            y = qy + t * dy
            if cy - hh - 1e-6 <= y <= cy + hh + 1e-6:
                candidates.append(t)
    if dy != 0:
        for by in (cy - hh, cy + hh):
            t = (by - qy) / dy
            x = qx + t * dx
            if cx - hw - 1e-6 <= x <= cx + hw + 1e-6:
                candidates.append(t)
    if not candidates:
        return px, py
    # P itself is at t=1 by construction (P = Q + 1*(dx,dy)) -- the
    # boundary crossing nearest that is the one Graphviz was already
    # aiming for, whether its own point fell just short of or past it.
    t = min(candidates, key=lambda tv: abs(tv - 1.0))
    return qx + t * dx, qy + t * dy


def _direction_ref(pts: list, from_end: bool) -> tuple:
    """Walks in from one end of an edge's point list to find the first
    point that differs from the terminal point at that end -- dot -Tplain
    sometimes repeats the same coordinate for the last 2+ points of a spline
    (a fully degenerate final segment, zero-length even before any
    transform), which leaves no direction to clip that endpoint against if
    only the immediately-adjacent point is consulted."""
    seq = list(reversed(pts)) if from_end else pts
    terminal = seq[0]
    for p in seq[1:]:
        if not _pts_close(p, terminal):
            return p
    return terminal


def bezier_path(pts: list) -> str:
    if len(pts) < 2: return ""
    cur = pts[0]
    d = f"M {cur[0]:.2f},{cur[1]:.2f}"
    i = 1
    while i + 2 < len(pts):
        c1, c2, end = pts[i], pts[i+1], pts[i+2]
        # dot -Tplain occasionally emits a curve whose final control point
        # c2 sits close to (not always exactly on) its own endpoint --
        # confirmed a real case ~0.8 units apart. That makes the exit
        # tangent (end - c2) a near-zero vector; marker-end's orient="auto"
        # reads that tangent to rotate the arrowhead, and a near-zero
        # vector is numerically unstable to normalize -- confirmed via a
        # real browser screenshot that this renders with no visible
        # arrowhead at all (not just a misrotated one). This eps only needs
        # to catch dot's own genuine near-duplicates; build_svg's endpoint
        # clipping separately shifts c2 by the same delta it moves the
        # endpoint by (see build_svg), which is the general fix for
        # *that* source of near-zero tangents -- this eps isn't meant to
        # (and shouldn't need to) absorb clip-introduced ones too.
        if _pts_close(c2, end, eps=2.0):
            d += f" L {end[0]:.2f},{end[1]:.2f}"
        else:
            d += (f" C {c1[0]:.2f},{c1[1]:.2f}"
                  f" {c2[0]:.2f},{c2[1]:.2f}"
                  f" {end[0]:.2f},{end[1]:.2f}")
        cur = end
        i += 3
    while i < len(pts):
        d += f" L {pts[i][0]:.2f},{pts[i][1]:.2f}"
        cur = pts[i]
        i += 1
    return d


def render_edge(edge: dict) -> str:
    pts   = edge["points"]
    if not pts: return ""
    style = edge.get("style", "solid").lower()
    dash  = ' stroke-dasharray="8,4"' if "dashed" in style else ""

    # Threagile marks lesser/background links (e.g. telemetry & audit
    # logging) as dashed -- render them distinctly smaller/fainter than
    # primary data flows instead of at equal visual weight. Primary links
    # are ink/black for stronger contrast; lesser ones stay muted gray.
    is_minor = "dashed" in style
    sw       = HAIRLINE * (0.7 if is_minor else 1.0)
    fontsize = EDGE_FONTSIZE_MINOR if is_minor else EDGE_FONTSIZE
    color    = MUTED if is_minor else INK
    mid      = "arr-muted" if is_minor else "arr-ink"

    path = bezier_path(pts)
    out  = [f'<path d="{path}" fill="none" stroke="{color}" stroke-width="{sw:.2f}"{dash} marker-end="url(#{mid})"/>']

    label = edge.get("label", "")
    if label and edge.get("lx") is not None:
        lx, ly = edge["lx"], edge["ly"]
        out.append(
            f'<text x="{lx:.2f}" y="{ly:.2f}" text-anchor="middle" '
            f'dominant-baseline="central" font-size="{fontsize}" '
            f'font-family="{FONT}" '
            f'fill="{color}">{html.escape(label)}</text>'
        )
    return "\n".join(out)


# ---------------------------------------------------------------------------
# 7. Cluster renderer
# ---------------------------------------------------------------------------

def render_cluster(cl: dict, bb: list, px_per_pt: float,
                   gh_pts: float, padding: float, shade_depth: int = 0,
                   icon_tags: list = None, for_print: bool = False,
                   label_fontsize: float = CLUSTER_FONTSIZE,
                   icon_size: float = ICON_SIZE, fill_type: str = None) -> str:
    x0, y0, x1, y1 = bb
    # Convert points to SVG pixels (Y-flip)
    sx0 = x0 * px_per_pt + padding
    sy0 = (gh_pts - y1) * px_per_pt + padding
    w   = (x1 - x0) * px_per_pt
    h   = (y1 - y0) * px_per_pt

    # Boundaries recede -- pastel fill (by boundary type) and a hairline
    # dashed border -- so they read as context rather than competing
    # visually with the nodes inside. The border and label share the
    # accent color (distinct from the muted edge lines) so a boundary
    # reads as one visual unit at a glance. shade_depth (how many
    # same-type ancestors this boundary is nested inside, from build_svg's
    # containment check) steps one shade darker per level. fill_type
    # defaults to this boundary's own type, but a type in FOLLOWS_RAMP_OF
    # (see that dict) passes its ramp type's key here instead, so its
    # shade_depth (already computed against that other type's ancestors by
    # the caller) is looked up in that type's own list rather than its own.
    shades = BOUNDARY_FILL.get(fill_type or cl.get("boundary_type", ""), [PAPER])
    fill = shades[min(shade_depth, len(shades) - 1)]
    out = [
        f'<rect x="{sx0:.2f}" y="{sy0:.2f}" width="{w:.2f}" height="{h:.2f}" '
        f'rx="{RADIUS}" fill="{fill}" stroke="{ACCENT}" stroke-width="{HAIRLINE}" stroke-dasharray="6,4"/>'
    ]

    label = cl["label"]
    if label:
        # Label and icon share the same top strip (icon inset from the
        # top-right corner, label centered at the same y) -- centered across
        # the full cluster width regardless of whether an icon is present,
        # since in practice the icon sits clear of the label at this size.
        label_cx = sx0 + w / 2
        # Baseline offset from the box's own top edge -- proportional to
        # label_fontsize rather than a flat pixel value, so every diagram
        # keeps the same visual clearance regardless of its own scale (see
        # DIAGRAM_SCALE_BASELINE_PX_PER_IN). 1.3, not render_node's 1.4
        # line-height multiplier -- 1.4 read as slightly too much
        # clearance for a single-line boundary label specifically (a
        # multi-line node label block has a different vertical rhythm to
        # match), confirmed by a direct visual pass after trying 1.4 first.
        label_y = sy0 + label_fontsize * 1.3
        out.append(
            f'<text x="{label_cx:.2f}" y="{label_y:.2f}" '
            f'text-anchor="middle" font-size="{label_fontsize:.2f}" font-weight="600" font-family="{FONT}" '
            f'fill="{ACCENT}">{html.escape(label)}</text>'
        )
    if icon_tags:
        left_tags  = [t for t in icon_tags if t in BOUNDARY_LEFT_CORNER_ICONS]
        right_tags = [t for t in icon_tags if t not in BOUNDARY_LEFT_CORNER_ICONS]
        if right_tags:
            out.append(render_icon(sx0 + w, sy0, right_tags, ACCENT, for_print=for_print, icon_size=icon_size))
        if left_tags:
            out.append(render_icon(sx0, sy0, left_tags, ACCENT, for_print=for_print, anchor="left", icon_size=icon_size))
    return "\n".join(out)


# ---------------------------------------------------------------------------
# 8. Build HTML
# ---------------------------------------------------------------------------

_CSS = """
* { box-sizing: border-box; margin: 0; padding: 0; }
body { font-family: Verdana, sans-serif; background: #f0f2f5; min-height: 100vh; }
header { padding: 14px 24px; background: #fff; border-bottom: 1px solid #dde1e9; display: flex; align-items: center; gap: 10px; }
header h1 { font-size: 16px; font-weight: 600; color: #1a1a2e; }
.badge { background: #eef2ff; color: #4361ee; font-size: 11px; font-weight: 700; padding: 3px 8px; border-radius: 20px; }
.canvas-wrap { padding: 24px; overflow: hidden; cursor: grab; user-select: none; }
.canvas-wrap.grabbing { cursor: grabbing; }
svg.dfd { display: block; background: #fff; border-radius: 8px; box-shadow: 0 2px 12px rgba(0,0,0,.08); transform-origin: top left; }

/* Click-to-highlight (see _HIGHLIGHT_JS): clicking an asset dims every
   node/edge not connected to it. Only active once svg.dfd carries
   hl-active, so a plain (non-JS, e.g. the bare .svg file) render is
   never affected -- these rules and the .node/.edge classes/data-*
   attributes they key off of are otherwise inert. */
svg.dfd .node { cursor: pointer; }
svg.dfd.hl-active .node,
svg.dfd.hl-active .edge { opacity: 0.15; transition: opacity 0.12s ease-out; }
svg.dfd.hl-active .node.hl-selected,
svg.dfd.hl-active .node.hl-connected,
svg.dfd.hl-active .edge.hl-connected { opacity: 1; }
svg.dfd.hl-active .edge.hl-connected path { stroke: #1a3a5c; stroke-width: 2.2px; }
svg.dfd.hl-active .node.hl-selected rect:first-of-type { stroke: #1a3a5c; stroke-width: 2.5px; }

/* Filter-links bar (see _FILTER_JS): picking a category dims every edge
   not classified into it (see classify_edge/data-category) -- nodes are
   never dimmed by this, only links, so the asset layout stays legible
   while tracing one kind of flow. Independent of click-to-highlight
   above: .dimmed forces opacity regardless of hl-active/hl-connected. */
.filter-bar { padding: 10px 24px; background: #fff; border-bottom: 1px solid #dde1e9; display: flex; align-items: center; gap: 8px; flex-wrap: wrap; }
.filter-label { font-size: 10px; font-weight: 700; letter-spacing: 0.08em; color: #8a8f98; margin-right: 2px; }
.filter-chip { font-family: Verdana, sans-serif; font-size: 11px; font-weight: 600; color: #555; background: #fff; border: 1px solid #dde1e9; border-radius: 20px; padding: 4px 12px; cursor: pointer; transition: all 0.12s ease-out; }
.filter-chip:hover { border-color: #b7bfcc; color: #1a1a2e; }
.filter-chip.active { color: #fff; background: #1a3a5c; border-color: #1a3a5c; }
svg.dfd .edge.dimmed { opacity: 0.06 !important; }
"""

# Two fixed-color markers rather than one shared marker with
# stroke="context-stroke" (SVG2) -- confirmed via a minimal test render that
# WeasyPrint doesn't support context-stroke and always paints such a marker
# black, which is wrong for MUTED (dashed/minor) edges. render_edge picks
# the id matching its own edge color.
ARROW_DEFS = """<defs>
  <marker id="arr-ink" viewBox="0 0 10 10" refX="9" refY="5"
          markerWidth="6" markerHeight="6" orient="auto">
    <path d="M1,2 L9,5 L1,8" fill="none" stroke="%(ink)s"
          stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
  </marker>
  <marker id="arr-muted" viewBox="0 0 10 10" refX="9" refY="5"
          markerWidth="6" markerHeight="6" orient="auto">
    <path d="M1,2 L9,5 L1,8" fill="none" stroke="%(muted)s"
          stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
  </marker>
</defs>""" % {"ink": INK, "muted": MUTED}

_JS = """
(function () {
  const wrap = document.querySelector('.canvas-wrap');
  const svg  = document.querySelector('svg.dfd');
  let scale = 1, tx = 0, ty = 0;
  let dragging = false, lastX = 0, lastY = 0;
  let downX = 0, downY = 0, dragMoved = false;

  function apply() {
    svg.style.transform = `translate(${tx}px,${ty}px) scale(${scale})`;
  }

  wrap.addEventListener('wheel', function (e) {
    e.preventDefault();
    const rect  = wrap.getBoundingClientRect();
    const mx    = e.clientX - rect.left;
    const my    = e.clientY - rect.top;
    const delta = e.deltaY < 0 ? 1.1 : 0.909;
    tx = mx - (mx - tx) * delta;
    ty = my - (my - ty) * delta;
    scale *= delta;
    scale = Math.min(Math.max(scale, 0.1), 10);
    apply();
  }, { passive: false });

  wrap.addEventListener('mousedown', function (e) {
    dragging = true; lastX = e.clientX; lastY = e.clientY;
    downX = e.clientX; downY = e.clientY; dragMoved = false;
    wrap.classList.add('grabbing');
  });
  window.addEventListener('mousemove', function (e) {
    if (!dragging) return;
    if (!dragMoved && (Math.abs(e.clientX - downX) > 4 || Math.abs(e.clientY - downY) > 4)) {
      dragMoved = true;
    }
    tx += e.clientX - lastX; ty += e.clientY - lastY;
    lastX = e.clientX; lastY = e.clientY;
    apply();
  });
  window.addEventListener('mouseup', function () {
    dragging = false; wrap.classList.remove('grabbing');
  });

  // A pan-drag ends with the mouse over whatever node/background the
  // cursor happens to land on, and the browser fires a normal 'click'
  // there regardless of the drag in between -- left unchecked, panning
  // across a node re-selects it and panning across empty canvas clears
  // the highlight mid-drag (see _HIGHLIGHT_JS). Swallow that one click in
  // the capturing phase (before it reaches any node's or the svg's own
  // click listener) whenever real movement happened between mousedown and
  // mouseup, so only a genuine, near-stationary click acts as a click.
  wrap.addEventListener('click', function (e) {
    if (dragMoved) { e.stopPropagation(); dragMoved = false; }
  }, true);
})();
"""

# Click an asset to highlight it and everything it's directly connected to
# (its own communication links, both as source and target); dims everything
# else. Click the same asset again, or click empty canvas, to clear it.
# Keyed off the .node/.edge classes and data-id/data-tail/data-head
# attributes build_svg's node- and edge-drawing loops attach to every <g> --
# opaque Graphviz-assigned ids (e.g. "4069313389"), not Threagile's own
# technical-asset ids, but stable and unique per node either way, which is
# all this needs to join edges back to their two endpoint nodes.
_HIGHLIGHT_JS = """
(function () {
  const svg = document.querySelector('svg.dfd');
  if (!svg) return;
  const nodes = Array.from(svg.querySelectorAll('.node'));
  const edges = Array.from(svg.querySelectorAll('.edge'));
  let selectedId = null;

  function clear() {
    svg.classList.remove('hl-active');
    nodes.forEach(n => n.classList.remove('hl-selected', 'hl-connected'));
    edges.forEach(e => e.classList.remove('hl-connected'));
    selectedId = null;
  }

  function select(id) {
    clear();
    selectedId = id;
    svg.classList.add('hl-active');
    const connected = new Set([id]);
    edges.forEach(function (e) {
      const tail = e.getAttribute('data-tail'), head = e.getAttribute('data-head');
      if (tail === id || head === id) {
        e.classList.add('hl-connected');
        connected.add(tail);
        connected.add(head);
      }
    });
    nodes.forEach(function (n) {
      const nid = n.getAttribute('data-id');
      if (nid === id) n.classList.add('hl-selected');
      else if (connected.has(nid)) n.classList.add('hl-connected');
    });
  }

  nodes.forEach(function (n) {
    n.addEventListener('click', function (evt) {
      evt.stopPropagation();
      const id = n.getAttribute('data-id');
      if (id === selectedId) clear();
      else select(id);
    });
  });
  svg.addEventListener('click', clear);
})();
"""

# Filter-links bar: picking a chip dims every edge whose data-category
# (see classify_edge) doesn't include it, back to "all" un-dims everything.
# data-category is a space-separated list, not always a single value -- a
# link can be tagged into more than one category at once (e.g. a shared
# perimeter hop carrying both authentication and ordinary chat traffic),
# so this checks membership, not equality. Only touches .edge elements --
# deliberately leaves nodes alone (see _CSS) so the asset layout stays
# legible while tracing one kind of flow.
_FILTER_JS = """
(function () {
  const svg = document.querySelector('svg.dfd');
  if (!svg) return;
  const edges = Array.from(svg.querySelectorAll('.edge'));
  const chips = Array.from(document.querySelectorAll('.filter-chip'));

  chips.forEach(function (chip) {
    chip.addEventListener('click', function () {
      chips.forEach(c => c.classList.remove('active'));
      chip.classList.add('active');
      const filter = chip.getAttribute('data-filter');
      edges.forEach(function (e) {
        const categories = (e.getAttribute('data-category') || '').split(' ');
        e.classList.toggle('dimmed', filter !== 'all' && !categories.includes(filter));
      });
    });
  });
})();
"""

# ---------------------------------------------------------------------------
# 6b. Edge classification for the filter-links bar
# ---------------------------------------------------------------------------

def classify_edge(tail_label: str, head_label: str,
                   vpc_by_label: dict = None,
                   devops_link_pairs: set = None,
                   path_tags_by_pair: dict = None) -> set:
    """Buckets one edge into one or more of "mission", "telemetry",
    "identity", "network" for the filter-links bar (see FILTER_CATEGORIES)
    -- a link can be more than one at once (e.g. a shared perimeter hop
    that carries both authentication and ordinary chat traffic is both
    Identity Path and Network Path), so this returns a set, checked in
    this priority order (not independent conditions -- later checks are
    skipped once something above them already matched):

    1. Explicit path:<category> tag(s) on the communication_link itself
       (03-tags-lib.yml's "COMMUNICATION LINK PATH-FILTER TAGS") --
       deterministic, authored intent, always wins when present, and is
       the only way an edge ends up in more than one category. This is
       the ONLY way a link becomes "identity" -- Threagile has no
       first-class field to infer it from (an earlier version guessed
       from endpoint `technology`, e.g. identity-provider, but that's a
       real inference, not a structural fact, and both modeled apps were
       already fully tagged anyway -- an untagged identity link now shows
       up as mission/network via the checks below instead of silently
       guessing, which is a more honest failure mode: obviously
       incomplete rather than confidently wrong).
    2. Failing an explicit tag, a usage:devops link (confirmed, across
       every modeled app so far, to always be a "Log Forwarding" hop to a
       logging/SIEM sink) is telemetry even if one endpoint is also
       network-typed infrastructure (e.g. a firewall's own telemetry hop)
       -- that specific hop is about shipping logs, not about the
       firewall's routing role.
    3. Failing that, Network Path is inferred structurally: the two
       endpoints resolve (via vpc_by_label, see compute_vpc_by_asset_id)
       to different enclosing VPC/VNet trust boundaries, i.e. the link
       actually crosses one -- a real structural fact, not a guess.
    4. "mission" is the default when nothing above matched."""
    if path_tags_by_pair:
        tagged = path_tags_by_pair.get((tail_label, head_label))
        if tagged:
            return set(tagged)
    if devops_link_pairs and (tail_label, head_label) in devops_link_pairs:
        return {"telemetry"}
    if vpc_by_label:
        tail_vpc, head_vpc = vpc_by_label.get(tail_label), vpc_by_label.get(head_label)
        if tail_vpc != head_vpc:
            return {"network"}
    return {"mission"}


# (css value suffix, filter-bar button label) -- "all" is handled separately
# in the filter-bar HTML/JS since it's "show everything", not a category any
# edge is ever classified as.
FILTER_CATEGORIES = [
    ("mission",   "MISSION FLOWS"),
    ("telemetry", "LOG/TELEMETRY"),
    ("identity",  "IDENTITY PATH"),
    ("network",   "NETWORK PATH"),
]

# The data-asset diagram's edges are data-asset<->technical-asset "stored
# by"/"processed by" relationships, not communication links between two
# technical assets -- classify_edge's mission/telemetry/identity/network
# buckets have no real signal to work from there (vpc_by_label only ever
# resolves technical-asset labels, so one endpoint of every such edge
# looks up as None, which used to make nearly every edge misclassify as
# "network" purely because None != some real VPC id). This diagram has
# its own real structural fact instead -- solid ("stored") vs dashed
# ("processed/transits", see render_edge) -- already the exact
# distinction the report text below this diagram describes.
FILTER_CATEGORIES_DATA_ASSET = [
    ("stored",    "STORED"),
    ("processed", "PROCESSED / TRANSITS"),
]


def build_svg(dot_source: str, title: str = "Data Flow Diagram",
              target_width: int = 3200, padding: int = 50,
              print_size_in: tuple = None,
              confidentiality_by_label: dict = None,
              icon_by_label: dict = None,
              vpc_by_label: dict = None,
              devops_link_pairs: set = None,
              path_tags_by_pair: dict = None,
              for_print: bool = False) -> str:
    """Returns a bare <svg>...</svg> fragment (no XML declaration, no HTML
    wrapper) laid out at Graphviz's own coordinates via `dot -Tplain`, with
    our own restyled shapes/palette drawn on top instead of Threagile's.

    print_size_in, if given, is (max_width_in, max_height_in): the root
    <svg> gets explicit width/height in those units (fit-to-box, aspect
    preserved) instead of raw pixel dimensions, for direct embedding at a
    known print size -- this SVG carries no Graphviz-dpi-derived internal
    transform the way Threagile's own output does, so plain viewBox-driven
    scaling is safe here (see dot-wrapper/dot for that history).

    confidentiality_by_label, if given, maps a node's rendered label text to
    a confidentiality level (see CONFIDENTIALITY_FILL) -- the data-asset
    diagram's stand-in for the data-flow diagram's boundary-type shading,
    since it has no trust boundaries of its own to color by. The .gv source
    alone doesn't carry this (Threagile's own per-node fillcolor there is
    uniform, not confidentiality-derived), so the caller must supply it from
    the model YAML.

    icon_by_label, if given, maps a node or trust-boundary's rendered label
    text to a list of ICON_FILES keys, in tag order (see that dict and
    03-tags-lib.yml's "DIAGRAM ICON TAGS") -- a node renders all of them as
    a side-by-side row (see render_node), a trust boundary's corner badge
    only ever shows the first. Same reasoning as confidentiality_by_label:
    an asset's icon: tag(s) live in the model YAML, not the .gv source, so
    the caller supplies this lookup rather than it being inferred here.

    vpc_by_label, devops_link_pairs, and path_tags_by_pair, if given, feed
    each edge's data-category attribute (see classify_edge()) for the
    standalone HTML diagrams' filter-links bar -- same reasoning again,
    since each asset's enclosing VPC/VNet, a link's `usage`, and a link's
    own path: tag(s) all live in the model YAML, not the .gv source. All
    three are optional and independent of each other; all being None just
    means every edge classifies as "mission".

    for_print, if True, swaps any icon needing the WeasyPrint gradient
    workaround (see _icon_needs_print_raster) for a rasterized PNG version
    instead of the vendored SVG -- pass this only for the copy actually
    handed to WeasyPrint (generate_report.py's PDF embedding), never for
    the standalone SVG/HTML files, which render the affected icon's SVG
    correctly as-is."""

    plain        = run_dot_plain(dot_source)
    layout       = parse_plain(plain)
    dot_attrs    = parse_dot_node_attrs(dot_source)
    cluster_defs = parse_dot_cluster_attrs(dot_source)
    cluster_bbs, edge_xlp = parse_dot_cluster_bbs(dot_source)
    edge_xlabels = parse_dot_edge_xlabels(dot_source)

    g = layout["graph"]
    if not g:
        sys.exit("ERROR: could not parse graph info.")

    gw_in, gh_in = g["width"], g["height"]
    available    = target_width - 2 * padding
    px_per_in    = available / gw_in if gw_in > 0 else 72.0
    px_per_pt    = px_per_in / PPI
    canvas_w     = gw_in * px_per_in + 2 * padding
    canvas_h     = gh_in * px_per_in + 2 * padding
    gh_pts       = gh_in * PPI  # graph height in points for Y-flip

    # See DIAGRAM_SCALE_BASELINE_PX_PER_IN's own comment -- keeps label
    # text and icons sized proportionally to this diagram's own boxes
    # rather than everyone sharing the same fixed pixel constants
    # regardless of how big or small this diagram's boxes happen to render.
    diagram_scale = px_per_in / DIAGRAM_SCALE_BASELINE_PX_PER_IN
    diagram_scale = max(DIAGRAM_SCALE_MIN, min(DIAGRAM_SCALE_MAX, diagram_scale))
    cluster_fontsize    = CLUSTER_FONTSIZE * diagram_scale
    boundary_icon_size  = ICON_SIZE * diagram_scale
    node_icon_target    = NODE_ICON_TARGET_SIZE * diagram_scale

    def tx(x): return x * px_per_in + padding
    def ty(y): return (gh_in - y) * px_per_in + padding

    if print_size_in:
        # px_per_in SVG user-units == 1 real inch by construction (that's
        # what it was derived to do above), so canvas_w/h divided by it is
        # already the true print size in inches -- no DPI assumption needed.
        max_w_in, max_h_in = print_size_in
        native_w_in, native_h_in = canvas_w / px_per_in, canvas_h / px_per_in
        scale = min(max_w_in / native_w_in, max_h_in / native_h_in)
        size_attrs = f'width="{native_w_in*scale:.2f}in" height="{native_h_in*scale:.2f}in" '
    else:
        size_attrs = f'width="{canvas_w:.0f}" height="{canvas_h:.0f}" '

    parts = [
        f'<svg class="dfd" {size_attrs}'
        f'viewBox="0 0 {canvas_w:.2f} {canvas_h:.2f}" '
        f'xmlns="http://www.w3.org/2000/svg" role="img">',
        f'<title>{html.escape(title)}</title>',
        ARROW_DEFS,
        f'<rect width="{canvas_w:.2f}" height="{canvas_h:.2f}" fill="{PAPER}"/>',
    ]

    # Clusters (trust boundaries) — sorted by area descending so outer ones
    # render first. Shade depth (for same-type nesting, e.g. a
    # network-cloud-provider boundary inside another network-cloud-provider
    # boundary) is derived from actual geometric containment against
    # already-placed (necessarily larger-or-equal-area, i.e. more outer)
    # clusters, not DOT source order -- boundary nesting in the source has
    # no guaranteed outer-before-inner ordering.
    cl_map = {cl["id"]: cl for cl in cluster_defs}
    bb_items = []
    for cid, bb in cluster_bbs.items():
        if cid in cl_map:
            area = (bb[2]-bb[0]) * (bb[3]-bb[1])
            bb_items.append((area, cid, bb))
    bb_items.sort(reverse=True)

    def _bb_contains(outer, inner, eps=0.5):
        return (outer[0] - eps <= inner[0] and outer[1] - eps <= inner[1]
                and outer[2] + eps >= inner[2] and outer[3] + eps >= inner[3])

    placed = []  # (cid, bb) already rendered, outer-to-inner so far
    for _, cid, bb in bb_items:
        cl = cl_map[cid]
        # fill_type: see FOLLOWS_RAMP_OF -- a type there (execution-environment)
        # rides another type's own color ramp instead of having its own, so
        # depth is counted among ancestors of *that* type instead of its own
        # (which would always be 0, since e.g. a VM never nests inside another
        # VM), landing it on the next shade past its immediate parent's own.
        fill_type = FOLLOWS_RAMP_OF.get(cl.get("boundary_type", ""), cl.get("boundary_type", ""))
        depth = sum(
            1 for pcid, pbb in placed
            if cl_map[pcid].get("boundary_type") == fill_type
            and _bb_contains(pbb, bb)
        )
        # A boundary's corner badge now shows one icon per tag, in tag
        # order, as a row extending leftward from the corner -- same
        # side-by-side approach a node's own icon row already used below,
        # ported to render_icon/render_cluster (see those functions).
        cl_icons = (icon_by_label.get(cl["label"]) or []) if icon_by_label else []
        parts.append(render_cluster(cl, bb, px_per_pt, gh_pts, padding, shade_depth=depth, icon_tags=cl_icons, for_print=for_print,
                                     label_fontsize=cluster_fontsize, icon_size=boundary_icon_size, fill_type=fill_type))
        placed.append((cid, bb))

    # confidentiality_by_label is only ever passed for the data-asset
    # diagram (see its docstring above) -- reuse it as the signal to pick
    # that diagram's own, larger node font and its own edge-filter
    # categories (see the edge loop below) instead of adding a separate
    # caller-facing flag for the same distinction.
    is_data_asset = confidentiality_by_label is not None
    node_fontsize = (NODE_FONTSIZE_DATA_ASSET if is_data_asset else NODE_FONTSIZE) * diagram_scale

    # Per-node render info (resolved label and its wrapped lines) computed
    # once, ahead of both the edge loop and the node-drawing loop below, so
    # node_boxes (used to clip edge endpoints) and the actual drawn boxes
    # stay derived from the exact same node dimensions -- Graphviz's own
    # native w/h, never resized (see wrap_and_fit).
    node_render_info = {}
    for node in layout["nodes"]:
        nid = node["id"]
        extra = dot_attrs.get(nid, {})
        label = node["label"] or nid
        if extra.get("label"):
            better = extract_bold_text(extra["label"])
            if better and better != nid:
                label = better
        icon_tags = (icon_by_label.get(label) or []) if icon_by_label else []
        icon_tags = [t for t in icon_tags if _resolve_icon_file(t)]
        native_w = node["w"] * px_per_in
        lines, fitted_w = wrap_and_fit(label, native_w, fontsize=node_fontsize)
        native_h = node["h"] * px_per_in

        # A tagged icon is dropped entirely by render_node's own fit check
        # below NODE_ICON_MIN if the box is too short -- rather than let
        # that happen silently, grow the box height here (before node_boxes
        # and edge clipping are derived from it, so both stay consistent --
        # see wrap_and_fit's docstring on why a *shrink* done after the fact
        # breaks edge routing; growing before anything downstream reads
        # this value doesn't have that problem). Target NODE_ICON_TARGET_SIZE
        # (the fixed size every node icon now renders at), not just
        # NODE_ICON_MIN -- solving for the bare floor technically keeps the
        # icon visible but renders it at 12px against neighboring icons all
        # at the fixed default in the same diagram, which reads as broken
        # rather than intentional. Confirmed necessary in practice: Threagile
        # natively draws a human external entity (used_as_client_by_human:
        # true, octagon shape) taller than a machine one (box shape) -- a
        # deliberate distinction on Threagile's part, not something to paper
        # over by misrepresenting that field, but its shorter native box
        # otherwise silently drops or shrinks that machine-actor's own icon.
        if icon_tags:
            line_h = node_fontsize * 1.4
            total_h = line_h * len(lines)
            min_h = (node_icon_target + total_h + NODE_ICON_GAP) / 0.92
            native_h = max(native_h, min_h)

        node_render_info[nid] = {
            "label": label,
            "icon_tags": icon_tags,
            "lines": lines,
            "w": fitted_w,
            "h": native_h,
        }

    # Node bounding boxes in px, keyed by id -- built ahead of the edge loop
    # (nodes themselves are still drawn after edges, below) purely so edges
    # can clip their own endpoints onto them; see _clip_to_box.
    node_boxes = {}
    for node in layout["nodes"]:
        info = node_render_info[node["id"]]
        node_boxes[node["id"]] = (tx(node["x"]), ty(node["y"]), info["w"] / 2, info["h"] / 2)

    def _clip_and_shift(pts_px, idx, ctrl_idx, box, from_end):
        """Clips pts_px[idx] onto box's boundary, then translates
        pts_px[ctrl_idx] (that segment's own Bezier control point) by the
        exact same delta. Graphviz's own node size assumed an inscribed
        ellipse/cylinder curve; the rectangle we now draw fully contains
        that curve, so an edge approaching at an angle (not square onto an
        axis) can need a real, sometimes-large clip displacement -- moving
        only the endpoint would leave the control point behind, shrinking
        or reversing (end - control), the tangent marker-end's orient="auto"
        rotates the arrowhead from. Shifting both keeps that tangent
        exactly what it originally was, just translated, regardless of how
        far the clip itself needed to move the point."""
        q = _direction_ref(pts_px, from_end=from_end)
        old_pt = pts_px[idx]
        new_pt = _clip_to_box(*q, *old_pt, *box)
        pts_px[idx] = new_pt
        n = len(pts_px)
        ctrl_pos = ctrl_idx % n  # normalize negative indices before comparing
        if ctrl_pos not in (0, n - 1):
            dx, dy = new_pt[0] - old_pt[0], new_pt[1] - old_pt[1]
            cx2, cy2 = pts_px[ctrl_pos]
            pts_px[ctrl_pos] = (cx2 + dx, cy2 + dy)

    # Edges first (under nodes)
    for edge in layout["edges"]:
        pts_px = [(tx(px), ty(py)) for px, py in edge["points"]]
        if len(pts_px) >= 2:
            tail_box = node_boxes.get(edge["tail"])
            if tail_box:
                _clip_and_shift(pts_px, 0, 1, tail_box, from_end=False)
            head_box = node_boxes.get(edge["head"])
            if head_box:
                _clip_and_shift(pts_px, -1, -2, head_box, from_end=True)
        e2 = dict(edge, points=pts_px)
        key = (edge["tail"], edge["head"])

        # Use exact xlp position from dot -Tdot (Graphviz-computed, never overlaps)
        if key in edge_xlp:
            xlp_x, xlp_y = edge_xlp[key]
            e2["lx"] = xlp_x * px_per_pt + padding
            e2["ly"] = (gh_pts - xlp_y) * px_per_pt + padding
        elif edge.get("lx") is not None:
            e2["lx"] = tx(edge["lx"])
            e2["ly"] = ty(edge["ly"])

        # Attach xlabel text from DOT source
        if not e2.get("label") and key in edge_xlabels:
            e2["label"] = edge_xlabels[key]

        if is_data_asset:
            # See FILTER_CATEGORIES_DATA_ASSET -- classify_edge's
            # communication-link-based categories don't apply here; the
            # edge's own solid/dashed style (already how render_edge
            # decides "primary vs minor") is this diagram's real
            # stored-vs-processed distinction.
            style = edge.get("style", "solid").lower()
            categories = {"processed"} if "dashed" in style else {"stored"}
        else:
            tail_label = node_render_info.get(edge["tail"], {}).get("label", "")
            head_label = node_render_info.get(edge["head"], {}).get("label", "")
            categories = classify_edge(tail_label, head_label, vpc_by_label,
                                        devops_link_pairs, path_tags_by_pair)
        parts.append(f'<g class="edge" data-tail="{html.escape(edge["tail"])}" '
                     f'data-head="{html.escape(edge["head"])}" data-category="{" ".join(sorted(categories))}">')
        parts.append(render_edge(e2))
        parts.append('</g>')

    # Nodes on top
    for node in layout["nodes"]:
        info = node_render_info[node["id"]]
        cx = tx(node["x"])
        cy = ty(node["y"])
        node = dict(node, label=info["label"])
        fill_override = None
        if confidentiality_by_label:
            level = confidentiality_by_label.get(info["label"])
            fill_override = CONFIDENTIALITY_FILL.get(level)
        parts.append(f'<g class="node" data-id="{html.escape(node["id"])}">')
        parts.append(render_node(node, cx, cy, info["w"], info["h"], dot_attrs,
                                  info["lines"], fill_override=fill_override, icon_tags=info["icon_tags"],
                                  fontsize=node_fontsize, for_print=for_print,
                                  icon_target_size=node_icon_target))
        parts.append('</g>')

    parts.append('</svg>')
    return "".join(parts)


def build_html(dot_source: str, title: str = "Data Flow Diagram",
               target_width: int = 3200, padding: int = 50,
               confidentiality_by_label: dict = None,
               icon_by_label: dict = None,
               vpc_by_label: dict = None,
               devops_link_pairs: set = None,
               path_tags_by_pair: dict = None) -> str:

    svg = build_svg(dot_source, title=title, target_width=target_width, padding=padding,
                     confidentiality_by_label=confidentiality_by_label,
                     icon_by_label=icon_by_label,
                     vpc_by_label=vpc_by_label,
                     devops_link_pairs=devops_link_pairs,
                     path_tags_by_pair=path_tags_by_pair)

    # See FILTER_CATEGORIES_DATA_ASSET -- the data-asset diagram gets its
    # own filter set (stored/processed) instead of the data-flow diagram's
    # communication-link categories, which have no meaningful signal for
    # data-asset<->technical-asset edges.
    categories = FILTER_CATEGORIES_DATA_ASSET if confidentiality_by_label is not None else FILTER_CATEGORIES
    filter_chips = '<button class="filter-chip active" data-filter="all">ALL</button>' + "".join(
        f'<button class="filter-chip" data-filter="{value}">{label}</button>'
        for value, label in categories
    )

    return textwrap.dedent(f"""\
    <!DOCTYPE html>
    <html lang="en">
    <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>{html.escape(title)}</title>
    <style>{_CSS}</style>
    </head>
    <body>
    <header>
      <h1>{html.escape(title)}</h1>
      <span class="badge">DFD</span>
    </header>
    <div class="filter-bar">
      <span class="filter-label">FILTER LINKS:</span>
      {filter_chips}
    </div>
    <div class="canvas-wrap">
    {svg}
    </div>
    <script>{_JS}</script>
    <script>{_HIGHLIGHT_JS}</script>
    <script>{_FILTER_JS}</script>
    </body>
    </html>
    """)


# ---------------------------------------------------------------------------
# 9. CLI
# ---------------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser(description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    src = ap.add_mutually_exclusive_group(required=True)
    src.add_argument("--dot",   metavar="FILE")
    src.add_argument("--stdin", action="store_true")
    ap.add_argument("--out",     metavar="FILE", default="dfd.html")
    ap.add_argument("--title",   metavar="TEXT", default="Data Flow Diagram")
    ap.add_argument("--width",   metavar="N",    type=int, default=3200)
    ap.add_argument("--padding", metavar="N",    type=int, default=50)
    ap.add_argument("--dump-plain", action="store_true")
    args = ap.parse_args()

    dot_source = Path(args.dot).read_text() if args.dot else sys.stdin.read()

    if args.dump_plain:
        print(run_dot_plain(dot_source))
        return

    out = build_html(dot_source, title=args.title,
                     target_width=args.width, padding=args.padding)
    out_path = Path(args.out)
    out_path.write_text(out, encoding="utf-8")
    print(f"Written -> {out_path}  ({out_path.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()